### ISSUE TITLE
SMS/ConnectWise integration

### ISSUE THREAD

**Issue by jundis** [jundis/CWilio#8]
Goal would be to have SMS abilities through Slack which post updates to ConnectWise.

**Comment by joshuamsmith** [comment]
Obviously you'll be using Twilio! They have a good tutorial for building an SMS bot that got me up and running with a simple RSVP SMS system: https://www.twilio.com/blog/2016/09/fun-with-markov-chains-python-and-twilio-sms.html. The SMS stuff is near the end.

**Comment by jundis** [comment]
Oh of course. Just gotta get around to having time to do so

**Comment by jundis** [comment]
Spun this off into a new repository to keep things separate. Too much work will be going into SMS integration and it will have no cross with this except a few config values.

See https://github.com/jundis/CWilio-SMS for progress
